### ISSUE TITLE
STEP Files

### ISSUE THREAD

**Issue by MaxBareiss** [PCrnjak/Faze4-Robotic-arm#10]
This robot arm is awesome and I'm trying to make one. Inductive sensors with an 8mm body are too expensive, so I bought ones with an 18mm body and I'd like to adapt the parts to the new hole size. Are the original CAD files or STEP format CAD files publically available for this project to make it easier to modify?

**Comment by maokk** [comment]
I am also have  the  same problem, I am prepare to assemble this robot arm, but my joint3 stepper motor are a little bit different , its very ugly to cut after printed the Joint 3 cover.STL
