### ISSUE TITLE
high-level help

### ISSUE THREAD

**Issue by i-make-robots** [PCrnjak/Faze4-Robotic-arm#3]
Hi!  Your arm is gorgeous.  Would love to see some exploded diagrams or section diagrams in the documentation.

I have a visual simulator and firmware that should run IK for your robot and knows how to use acceleration for smoother motion.

https://github.com/MarginallyClever/Makelangelo-software is the firmware (supporting many kinematic models) and 

https://github.com/MarginallyClever/Robot-Overlord is the software (gradient descent IK, simulation, etc)

I hope it helps!

**Comment by PCrnjak** [comment]
I am really sorry i didnt see this. Yea i saw your robot - overlord software and i am planning to try it out, but first i want to get ROS working so it will take some time. 
Anyway when i start working on it i will keep you updated, it looks great thx!
